#  Copyright (C) 2020  Mind Audio Central
#
#  This file is part of mac_backend_api.
#
#  mac_backend_api is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  mac_backend_api is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with mac_backend_api.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.0.6 on 2020-06-16 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='A reference to the User instance', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id of the audio', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the audio', max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Url-safe representation of the audio title', max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short description for the audio', max_length=2000)),
                ('listen_count', models.IntegerField(default=0, editable=False, help_text='The number of times the audio has been played')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date and time the audio was uploaded')),
                ('is_public', models.BooleanField(default=False, help_text='Indicates if the audio should be shown on public indexes, it can only be viewed by those with its link')),
                ('authors', models.ManyToManyField(help_text='References to the authors audios', to='audio.Author')),
            ],
        ),
    ]
