#  Copyright (C) 2020  Mind Audio Central
#
#  This file is part of mac_backend_api.
#
#  mac_backend_api is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  mac_backend_api is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with mac_backend_api.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.0.6 on 2020-06-23 01:42

from django.db import migrations, models
import django.db.models.deletion
import mac_backend_api.audio.models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStream',
            fields=[
                ('id', models.UUIDField(editable=False, help_text='The unique ID of the stream', primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('1', 'mp3'), ('2', 'aac'), ('3', 'ogg'), ('5', 'wav')], help_text='The format of the audio stream', max_length=10)),
                ('bit_rate', models.IntegerField(help_text="The stream's bit-rate in hz")),
                ('file', models.FileField(help_text="The stream's audio file, it will be processed to match the format and bit_rate values", upload_to=mac_backend_api.audio.models.get_audio_stream_upload_path)),
                ('audio', models.ForeignKey(help_text='A reference to the Audio instance', on_delete=django.db.models.deletion.CASCADE, to='audio.Audio')),
            ],
        ),
    ]
