# Generated by Django 3.0.6 on 2020-06-23 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_audiostream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiostream',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique ID of the stream', primary_key=True, serialize=False),
        ),
    ]
