#  Copyright (C) 2020  Mind Audio Central
#
#  This file is part of mac_backend_api.
#
#  mac_backend_api is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  mac_backend_api is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with mac_backend_api.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.0.6 on 2020-06-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_auto_20200622_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiostream',
            name='allow_downloads',
            field=models.BooleanField(default=False, help_text='Indicates if file should offer a direct download link.'),
        ),
        migrations.AlterField(
            model_name='audiostream',
            name='format',
            field=models.CharField(choices=[('mp3', 'Mp3'), ('aac', 'Aac'), ('ogg', 'Ogg'), ('wav', 'Wav')], help_text='The format of the audio stream', max_length=10),
        ),
    ]
