# Generated by Django 3.0.6 on 2020-07-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20200629_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiostream',
            name='sample_rate',
            field=models.IntegerField(choices=[(44100, 'Low'), (48000, 'Average'), (88200, 'High'), (96000, 'Very High')], default=48000, help_text="The stream's sample-rate in hz"),
        ),
        migrations.AlterField(
            model_name='audiostream',
            name='bit_rate',
            field=models.IntegerField(choices=[(32000, 'Minimal'), (96000, 'Very Low'), (128000, 'Low'), (192000, 'Average'), (256000, 'High'), (320000, 'Very High'), (512000, 'Maximum')], default=192000, help_text="The stream's bit-rate in hz"),
        ),
    ]
