# Generated by Django 3.0.7 on 2020-07-19 17:38

from django.db import migrations, models
import django.db.models.deletion
import mac_backend_api.audio.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20200705_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique ID of the stream', primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('mp3', 'Mp3'), ('aac', 'Aac'), ('ogg', 'Ogg'), ('wav', 'Wav')], help_text='The format of the audio stream', max_length=10)),
                ('bit_rate', models.IntegerField(choices=[(32000, 'Minimal'), (96000, 'Very Low'), (128000, 'Low'), (192000, 'Average'), (256000, 'High'), (320000, 'Very High'), (512000, 'Maximum')], default=192000, help_text="The stream's bit-rate in hz")),
                ('sample_rate', models.IntegerField(choices=[(44100, 'Low'), (48000, 'Average'), (88200, 'High'), (96000, 'Very High')], default=48000, help_text="The stream's sample-rate in hz")),
                ('allow_downloads', models.BooleanField(default=False, help_text='Indicates if file should offer a direct download link.')),
                ('file', models.FileField(help_text="The stream's audio file, it will be processed to match the format and bit_rate values", upload_to=mac_backend_api.audio.models.get_audio_stream_upload_path)),
                ('audio', models.ForeignKey(help_text='A reference to the Audio instance', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='audio.Audio')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioStream',
        ),
    ]
