# Generated by Django 3.0.7 on 2020-07-21 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0007_auto_20200719_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='authors',
            field=models.ManyToManyField(help_text="References to the audio's authors", to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
