# Generated by Django 3.0.6 on 2020-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_auto_20200720_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'permissions': (('change_own', 'can change own audio'), ('delete_own', 'can delete own audio'))},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'permissions': (('change_own', 'can change own streams'), ('delete_own', 'can delete own streams'))},
        ),
        migrations.RemoveField(
            model_name='audio',
            name='slug',
        ),
        migrations.AlterField(
            model_name='stream',
            name='bit_rate',
            field=models.IntegerField(choices=[(32000, 'Minimum'), (64000, 'Low'), (96000, 'Average'), (128000, 'High'), (192000, 'Very High'), (256000, 'Maximum')], default=96000, help_text="The stream's bit-rate in hz"),
        ),
        migrations.AlterField(
            model_name='stream',
            name='sample_rate',
            field=models.IntegerField(choices=[(44100, 'Low'), (48000, 'Average'), (96000, 'High')], default=48000, help_text="The stream's sample-rate in hz"),
        ),
    ]
