# Generated by Django 3.0.6 on 2020-08-25 15:53

from django.db import migrations, models
import mac_backend_api.utils.random_id.random_id


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_auto_20200816_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.CharField(default=mac_backend_api.utils.random_id.random_id.random_id, editable=False, help_text='Unique id of the audio', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default=mac_backend_api.utils.random_id.random_id.random_id, editable=False, help_text='The unique ID of the like', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stream',
            name='id',
            field=models.CharField(default=mac_backend_api.utils.random_id.random_id.random_id, editable=False, help_text='The unique ID of the stream', max_length=14, primary_key=True, serialize=False),
        ),
    ]
